### ISSUE TITLE
Cascade weapon projectiles not being doubled with multishot + high energy weapons

### ISSUE THREAD

**Issue by Bertie690** [arcburnergit/RAD-FTL-MV-Addon#5]
As stated in the title, lightning weapons with High Energy Weapons and Multishot weapons will result in you firing a normal amount of shots with _normal damage_, effectively giving you -60% weapon charge speed for no benefit whatsoever.
Tested using Reaction cannon, ion cascade and tesla 1, should work for other lightning weapons
(also yes I'm using latest version)

https://github.com/arcburnergit/RAD-FTL-MV-Addon/assets/136088738/a997286b-2730-4894-b4b7-5d8cb352ff24

**Comment by Duodecimus** [comment]
I'm not sure why, but the lightning weapon class is explicitly called out as banned from multishot

`mods.rad.multiExclusions = {}`
`local multiExclusions = mods.rad.multiExclusions`
`multiExclusions["RAD_CLUSTER_MISSILE"] = true`
`multiExclusions["RAD_CLUSTER_MISSILE_2"] = true`
`multiExclusions["RAD_CLUSTER_MISSILE_3"] = true`
`multiExclusions["RAD_LIGHTNING_1"] = true`
`multiExclusions["RAD_LIGHTNING_2"] = true`
`multiExclusions["RAD_LIGHTNING_3"] = true`
`multiExclusions["RAD_LIGHTNING_ION"] = true`
`multiExclusions["RAD_LIGHTNING_FIRE"] = true`
`multiExclusions["RAD_BEAM_BURST_1"] = true`
`multiExclusions["RAD_BEAM_BURST_2"] = true`
`multiExclusions["RAD_BEAM_BURST_3"] = true`
`multiExclusions["RAD_LIGHT_BEAM"] = true`
`multiExclusions["RAD_TRASH_BEAM"] = true`
`multiExclusions["DRONE_LASER_DEFENSE_INVIS"] = true`
`multiExclusions["ARTILLERY_FLESH"] = true`
`multiExclusions["ARTILLERY_RAD_ZS"] = true`
`multiExclusions["ARTILLERY_RAD_SWTCH"] = true`
`multiExclusions["ARTILLERY_FLESH_ENEMY"] = true`
`multiExclusions["ARTILLERY_RAD_CORVETTE"] = true`

ingame names:
Cluster Missile MK I
Cluster Missile MK II
Prototype Cluster Missile
Tesla Cannon MK I
Tesla Cannon MK II
Tesla Cannon MK III
Ion Cascade Cannon
Re-Action Cannon
Burst Pinpoint Mark I
Burst Pinpoint Mark II
Burst Pinpoint Mark III
Light Pinpoint
Tractor Beam
Pinpoint Defender Drone (the drone's laser)
Fleshy Heart (hull repair artillery)
Zoltan Shield Generator (Zoltan shield artillery)
Switch Drive (crew teleport artillery)
Fleshy Heart (quest enemy flesh ship hull repair artillery)
Chaff Cannon (debris shield artillery)


I assume these are mostly excluded due to not really having a downside for being split. the splash damage of them isn't reduced at all, so the lightning/cluster weapons are just straight twice as good.

Though that does beg the question of why other R&D weapons with mostly non-direct damage effects aren't also on this list.  SS chargers, _Diffusion lasers_ and the shield drain beam are all incredibly good with multishot.

edit: while they look cool, Diffusion weapons are not strictly better, as the split projectiles inherit their damage from the original.

**Comment by Bertie690** [comment]
Interesting.
Assuming this is intentional game design, weapons exempt from Multishot duplication should just keep the High Energy Weapons functionality (and maybe also have the augment _mention_ which weapon series don't work with it). At the moment, you're basically paying 60 scrap (+20 scrap to internalize) to permanently halve your weapons' damage output.

**Comment by Duodecimus** [comment]
Maybe let them work specifically if you have both?
Theres still a communication issue for the player there, but most of these don't gain much from double damage, I think?

Making them unaffected by the 60% would be very difficult, I'm pretty sure.

**Comment by Duodecimus** [comment]
You know, I almost never take high energy weapons. -60% is vastly more than what double damage is worth. I very rarely survive runs taking that hit, unless I've somehow already gotten a forgemaster charge rate hull capstone.
And I almost always take multishot, as it provides either minor positive (a regular 1/1/15 weapon deals double crew damage) to extremely benefical effects (Experimental mine launcher spawns twice as many clones) for the low cost of 80 scrap.

Maybe the firerate cost should be lowered, or spread out? Putting -25% on both augments maybe.
Then a beam heavy build would actually look at taking high energy weapons, as odds are they're already wasting a bit of charge time popping shields, a step you could skip if your beam did twice as much base hull.

**Comment by arcburnergit** [comment]
This is something that needs to be fixed. its happening becuase Multishot weapon exclusions are there because those weapons cannot have their weapon damage halved, and so when using multishot on its own those weapons get the upside with no downside. I'll just make it ignore the exclusion list when you have both augments.
